name: Build Password Manager

on: [push]

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Raylib (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libraylib-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev

      - name: Install Raylib (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install raylib

      - name: Install Raylib (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install raylib:x64-windows
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Compile (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: g++ main.cpp -o drawer_linux -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

      - name: Compile (macOS)
        if: matrix.os == 'macos-latest'
        run: g++ main.cpp -o drawer_mac -lraylib -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL

      - name: Compile (Windows)
        if: matrix.os == 'windows-latest'
        run: g++ main.cpp -o drawer.exe -O2 -lraylib -lopengl32 -gdi32 -lwinmm -mwindows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drawer-${{ matrix.os }}
          path: |
            drawer*
            font.ttf
